version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.19.0
    - 4.20.0
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: eslint
    versions:
    - 7.22.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
